# Generated by Django 2.1 on 2018-08-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=200)),
                ('userID', models.CharField(max_length=100)),
                ('eMail', models.CharField(max_length=200)),
                ('citizenship', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('Manager', models.CharField(max_length=200)),
                ('subPOC', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('phoneNum', models.IntegerField()),
                ('faaBadge', models.CharField(max_length=200)),
                ('faaParking', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='taskOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=200)),
                ('completionDate', models.CharField(max_length=200)),
                ('taskToBeCompleted', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvForms.moveForm')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=200)),
                ('eMail', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('Manager', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('phoneNum', models.IntegerField()),
            ],
        ),
    ]
