# Generated by Django 2.1 on 2018-08-24 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveform',
            name='publication_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
