# Generated by Django 2.1 on 2018-08-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0002_moveform_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveform',
            name='userID',
        ),
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
