# Generated by Django 2.1 on 2018-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0005_auto_20180824_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
