# Generated by Django 2.1 on 2018-08-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0006_auto_20180824_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveform',
            name='publication_date',
        ),
    ]
