# Generated by Django 2.1 on 2018-08-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0008_moveform_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveform',
            name='publication_date',
        ),
    ]
