# Generated by Django 2.1 on 2018-08-24 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0011_auto_20180824_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime, editable=False),
        ),
    ]
