# Generated by Django 2.1 on 2018-08-25 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0013_auto_20180824_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 25, 3, 24, 19, 738373, tzinfo=utc)),
        ),
    ]
