# Generated by Django 2.1 on 2018-08-25 03:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0014_auto_20180824_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
