# Generated by Django 2.1 on 2018-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0015_auto_20180824_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveform',
            old_name='citizenship',
            new_name='Citizenship',
        ),
        migrations.RenameField(
            model_name='moveform',
            old_name='company',
            new_name='Company',
        ),
        migrations.AlterField(
            model_name='moveform',
            name='comments',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='moveform',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
