# Generated by Django 2.1 on 2018-08-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0016_auto_20180826_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveform',
            name='eMail',
            field=models.EmailField(max_length=254),
        ),
    ]
