# Generated by Django 2.1 on 2018-08-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0017_auto_20180826_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveform',
            old_name='fName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='moveform',
            old_name='lName',
            new_name='Last_Name',
        ),
    ]
