# Generated by Django 2.1 on 2018-08-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0019_auto_20180827_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
