# Generated by Django 2.1 on 2018-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0020_auto_20180827_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
