# Generated by Django 2.1 on 2018-08-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0023_auto_20180829_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='relation',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='relation',
            field=models.ManyToManyField(to='mvForms.moveForm'),
        ),
    ]
