# Generated by Django 2.1 on 2018-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0024_auto_20180829_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='assignedTo',
            field=models.CharField(choices=[('patrick', 'Patrick'), ('test', 'Test'), ('third', 'Third')], default='patrick', max_length=20),
        ),
    ]
