# Generated by Django 2.1 on 2018-08-29 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0025_assignedtask_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='assignedTo',
            field=models.CharField(choices=[('patrick', 'Patrick'), ('david', 'David'), ('sean', 'Sean'), ('michelle', 'Michelle'), ('barbra', 'Barbra')], default='patrick', max_length=20),
        ),
        migrations.RemoveField(
            model_name='assignedtask',
            name='relation',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='relation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mvForms.moveForm'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='task',
            field=models.TextField(),
        ),
    ]
