# Generated by Django 2.1 on 2018-08-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0026_auto_20180829_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvForms.moveForm'),
        ),
    ]
