# Generated by Django 2.1 on 2018-08-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvForms', '0027_auto_20180829_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedtask',
            old_name='relation',
            new_name='relate',
        ),
    ]
